export const RISK_SCENARIOS = [
  { q: 'A mysterious door appears. Do you open it?', safe: 'Stay back', risk: 'Open it' },
  { q: 'Invest your savings: guaranteed 5% or 50% chance of 20%?', safe: '5% guaranteed', risk: '50% chance of 20%' },
  { q: 'Move to a new city for a dream job with no friends there?', safe: 'Stay comfortable', risk: 'Take the leap' },
  { q: 'Share your honest opinion in a group who disagrees?', safe: 'Stay silent', risk: 'Speak your mind' },
  { q: 'Try an extreme sport you\'ve never done?', safe: 'Watch others', risk: 'Jump in' },
  { q: 'Start a business with your savings and no income for 6 months?', safe: 'Keep job security', risk: 'Start the business' },
  { q: 'Trust a stranger\'s shortcut through an unknown path?', safe: 'Take known route', risk: 'Follow the shortcut' },
  { q: 'Enter a contest you could win but might embarrass yourself?', safe: 'Skip it', risk: 'Enter the contest' },
  { q: 'Try a highly experimental treatment for a minor ailment?', safe: 'Traditional medicine', risk: 'Experimental trial' },
  { q: 'Invest in a startup by a friend with no track record?', safe: 'Keep money in bank', risk: 'Invest in friend' },
  { q: 'Quit a steady job to pursue a passion project?', safe: 'Work part-time on passion', risk: 'Full-time leap' },
  { q: 'Confront a superior about an unfair policy?', safe: 'Wait for change', risk: 'Direct confrontation' },
  { q: 'Invest in a volatile cryptocurrency with potential 10x?', safe: 'Index funds', risk: 'Crypto investment' },
  { q: 'Move in with a partner you\'ve known for 3 months?', safe: 'Wait 6 more months', risk: 'Move in now' },
  { q: 'Submit your art to a major international festival?', safe: 'Local gallery', risk: 'Major festival' },
];

export const LOOP_QUESTIONS = [
  { q: 'If you could change one thing about your life right now, you would...', opts: ['Change my career path', 'Improve my relationships', 'Move to a new place', 'Change nothing'] },
  { q: 'When you feel overwhelmed, the thing that helps most is...', opts: ['Being alone and quiet', 'Talking to someone', 'Doing something physical', 'Distracting myself'] },
  { q: 'The way you usually handle a hard decision is...', opts: ['Think it through alone', 'Ask for advice', 'Go with your gut', 'Delay as long as possible'] },
  { q: 'If your week had a color, it would be...', opts: ['Grey — heavy and flat', 'Yellow — anxious and bright', 'Blue — calm but lonely', 'Red — intense and fast'] },
  { q: 'When something goes wrong, your first instinct is...', opts: ['Blame yourself', 'Analyze what happened', 'Move on quickly', 'Feel paralyzed'] },
  { q: 'Your biggest fear about the future is...', opts: ['Being alone', 'Failure', 'Boredom', 'Loss of control'] },
  { q: 'The most important thing for a happy life is...', opts: ['Security', 'Freedom', 'Connection', 'Purpose'] },
  { q: 'If you had an extra 4 hours every day, you would...', opts: ['Sleep', 'Work more', 'Pursue a hobby', 'Spend with family'] },
  { q: 'When you think about your past, you mostly feel...', opts: ['Nostalgia', 'Regret', 'Gratitude', 'Confusion'] },
  { q: 'The thing you value most in others is...', opts: ['Loyalty', 'Honesty', 'Kindness', 'Intelligence'] },
  { q: 'Your preferred way to spend a Saturday night is...', opts: ['Big party', 'Quiet dinner', 'Gaming/Movie at home', 'Working/Studying'] },
  { q: 'If you could know the date of your death, would you?', opts: ['Yes, definitely', 'No, never', 'Maybe if I could change it', 'Undecided'] },
];

export const TIMED_DECISIONS = [
  { q: "You're at a restaurant. Pick quickly!", opts: ["Pasta", "Pizza"] },
  { q: "Someone asks for a favor. Answer now!", opts: ["Yes", "No"] },
  { q: "Choose a movie genre.", opts: ["Horror", "Comedy"] },
  { q: "Select a weekend vibe.", opts: ["Active", "Relaxed"] },
  { q: "Pick a travel style.", opts: ["Solo", "Group"] },
  { q: "Choose a superpower.", opts: ["Flight", "Invisibility"] },
  { q: "Pick a beverage.", opts: ["Coffee", "Tea"] },
  { q: "Select a season.", opts: ["Summer", "Winter"] },
  { q: "Spend savings or invest?", opts: ["Spend", "Invest"] },
  { q: "Beach or mountains?", opts: ["Beach", "Mountains"] },
  { q: "Morning bird or night owl?", opts: ["Morning", "Night"] },
  { q: "Sweet or savory?", opts: ["Sweet", "Savory"] },
  { q: "Cat or dog?", opts: ["Cat", "Dog"] },
  { q: "eBook or physical book?", opts: ["eBook", "Physical"] },
  { q: "City life or country life?", opts: ["City", "Country"] },
  { q: "Call or text?", opts: ["Call", "Text"] },
  { q: "Mac or PC?", opts: ["Mac", "PC"] },
  { q: "Fiction or Non-fiction?", opts: ["Fiction", "Non-fiction"] },
  { q: "Action or Romance?", opts: ["Action", "Romance"] },
  { q: "Run or Walk?", opts: ["Run", "Walk"] },
];

export const PERFECT_ROUNDS = [
  { q: 'Which word best describes today?', opts: ['Okay', 'Fine', 'Alright', 'Decent'] },
  { q: 'Best way to start a morning?', opts: ['Quiet coffee alone', 'Slow coffee alone', 'Peaceful tea alone', 'Calm music alone'] },
  { q: 'The feeling right now is closest to...', opts: ['Tired', 'Drained', 'Exhausted', 'Weary'] },
  { q: 'If you could rest anywhere, it would be...', opts: ['A quiet room', 'A calm room', 'A still room', 'A silent room'] },
  { q: 'The weekend activity that sounds best?', opts: ['Stay in and rest', 'Be home and relax', 'Chill at home', 'Unwind indoors'] },
  { q: 'Which sounds most like how you feel socially?', opts: ['Comfortable alone', 'Happy alone', 'Okay being alone', 'Content alone'] },
  { q: 'The most soothing sound would be...', opts: ['Falling rain', 'Gentle wind', 'Distant waves', 'Soft white noise'] },
  { q: 'If you had to pick a texture for comfort...', opts: ['Soft wool', 'Smooth silk', 'Cool cotton', 'Fuzzy fleece'] },
  { q: 'Your favorite time of day for thinking...', opts: ['Pre-dawn', 'Late morning', 'Golden hour', 'Deep night'] },
  { q: 'The best simple gift you could receive...', opts: ['A handwritten note', 'A favorite snack', 'A fresh flower', 'A quiet moment'] },
  { q: 'Which color reflects your inner peace?', opts: ['Pale blue', 'Soft sage', 'Warm beige', 'Cool lavender'] },
  { q: 'The best way to spend 10 minutes unplugged...', opts: ['Deep breathing', 'Looking out window', 'Light stretching', 'Closing your eyes'] },
];

export const INTEREST_ACTIVITIES = [
  { emoji: '🎨', label: 'Painting', category: 'creative' },
  { emoji: '🎵', label: 'Music', category: 'creative' },
  { emoji: '📚', label: 'Reading', category: 'intellectual' },
  { emoji: '🌿', label: 'Gardening', category: 'nature' },
  { emoji: '🍳', label: 'Cooking', category: 'practical' },
  { emoji: '🏃', label: 'Running', category: 'physical' },
  { emoji: '🎮', label: 'Gaming', category: 'entertainment' },
  { emoji: '✍️', label: 'Writing', category: 'creative' },
  { emoji: '🧘', label: 'Meditation', category: 'wellbeing' },
  { emoji: '🎭', label: 'Acting', category: 'creative' },
  { emoji: '🚴', label: 'Cycling', category: 'physical' },
  { emoji: '📷', label: 'Photography', category: 'creative' },
  { emoji: '🎬', label: 'Films', category: 'entertainment' },
  { emoji: '🌍', label: 'Travel', category: 'adventure' },
  { emoji: '🤝', label: 'Volunteering', category: 'social' },
  { emoji: '🧩', label: 'Puzzles', category: 'intellectual' },
];
